function patient = newPatient()

patient = struct('id', {}, 'lungs', {}, 'body', {}, ...
                         'lungmask', {}, 'bodymask', {}, ...
                         'coreg', {}, 'parmslung', {}, 'parmsbody', {}, ...
                         'analysis', {}, 'dataver', 0.3, 'threshold', {}, ...
                         'mean_noise', {}, 'hetero_images', {}, 'hetero_score', {}, ...
                         'lung_function', {}, 'lung_SNR', {}, 'body_SNR', {}, 'mean_hetero', {});
% patient(1).id = 'newPatient';
% patient(1).dataver = 0.3;
% patient(1).lung_function  = lungfunc;

end