function patient = newPatient

patient = struct('id', '', 'lung', {}, 'body', {}, ...
                         'lungmask', {}, 'bodymask', {}, ...
                         'coreg', {}, 'parmslung', {}, 'parmsbody', {}, ...
                         'analysis', {}, 'dataver', 0.02, 'threshold', {}, ...
                         'mean_noise', {});
end